### ISSUE TITLE
Create separate Renderable Object

### ISSUE THREAD

**Issue by ShawnieBoy** [lodici/magarena-cardbuilder#19]
An object created and referred to in cardBuilder to replace references to MagicCard/MagicCardDefintion. Built from a sent MagicCard or MagicCardDefinition.

_Copied from original issue: magarena/magarenaCardBuilder#19_

**Comment by ShawnieBoy** [comment]
beginning work on this with 4a97cbf93bcb5922fb15d129f7418083c6ac240a

**Comment by melvinzhang** [comment]
Looks more like RenderInfo than Renderable. The concept of Renderable is
similar to that of Java's Comparable, it is an interface. Each class we
want to be able to render implements the necessary methods themselves as
the know best their internal data and how to generate the necessary info.

**Comment by ShawnieBoy** [comment]
Oh I see, so more like a MagicCard.renderable()?

**Comment by melvinzhang** [comment]
No, as in an interface with the methods the card builder calls. Similar to
how sort calls compareTo. The card builder takes an object that implements
Renderable with methods like getSubtypes etc

**Comment by lodici** [comment]
See https://docs.oracle.com/javase/tutorial/java/concepts/interface.html.

Create an interface class, IRenderableCard and add the method signatures that CardBuilder will call.

Implement this interface in the required classes, eg. ``public class MagicCardDefinition implements IRenderableCard``.

Provide implementation for each method defined in IRenderableCard. Java will not compile otherwise.

Update CardBuilder to code against IRenderableCard only. If you have done it right then there should be no references to MagicCardDefinition, MagicCard, etc.

Starting point: in CardBuilder replace 

```
public static BufferedImage getCardImage(final MagicCardDefinition cardDef) {...}
public static BufferedImage getCardImage(final MagicCard card) {...}
```

with 

```
public static BufferedImage getCardImage(final IRenderableCard card) {...}
```

**Comment by ShawnieBoy** [comment]
Thanks @lodici I'll look into it :+1:

**Comment by ShawnieBoy** [comment]
Finally got my head round it I think :grinning:

**Comment by ShawnieBoy** [comment]
Pushed my result - nothing's broken (fingers crossed) Please have a look
